dist: bionic
language: python
python:
  - "3.6.10"
  # - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt -r dev_requirements.txt
  - pip freeze
# command to run tests
script:
  - pytest -vv